# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               darrylcauldwell.com
tagline:             'On a journey around the datacenter and public cloud.'
description:         'On a journey around the datacenter and public cloud.'
url:                 http://darrylcauldwell.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Darryl Cauldwell
  url:               https://twitter.com/potato_heads
  email:             darryl_cauldwell@gmail.com
  github:            darrylcauldwell
  twitter:           potato_heads
  linkedin:          darryl-cauldwell-82156333

# Custom vars
version:             1.0.0
gems: 
  - jekyll-paginate
  - jekyll-sitemap

relative_permalinks: false