# Site settings
title: darrylcauldwell.com
email: darryl.cauldwell@gmail.com
description: A collection of blog posts based around virtualising the datacenter and leveraging the public cloud.
baseurl: ""
url: "http://darrylcauldwell.com"
twitter_username: potato_heads
github_username:  darrylcauldwell

# Build settings
markdown: kramdown