[[main]]
  name = "Home"
  url = ""
  weight = -110
[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/darrylcauldwell/"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/darrylcauldwell/"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/darryl-cauldwell-82156333/"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"